### ISSUE TITLE
feat: permissions for users and groups by taxonomy

### ISSUE THREAD

**Issue by masetto** [Regaez/grav-plugin-api#58]
Hi, now if `auth: true` all users with access can post, patch and delete pages. Is it complicated to provide different permissions for users and groups for page taxonomies? For example, the blogger group can add/edit/delete only pages with  `{'@taxonomy':{'category': 'blog'}`.
Thanks

**Comment by Regaez** [comment]
While I had not considered permission at a taxonomy level, I was planning to at least make it role-based, where roles would be added to individual users account in order to grant them different levels of access. Please see #4 

I would prioritise the role issue first, but I think that approach could potentially be extended to function on a taxonomy basis.

**Comment by Regaez** [comment]
@masetto This is totally feasible. We can generate custom roles based on taxonomy and values existing within the Grav site, which you can assign to a user/group. They are currently generated as `api.taxonomy_{name}___{value}`. For example:

_accounts/bob.yaml_
```yaml
access:
  api:
    pages_read: false
    page_edit: false
    pages_delete: false
    taxonomy_category___blog: true
```
Will allow the user `bob` access to any pages with the following taxonomy in the frontmatter:

```yaml
taxonomy:
  category: blog
```
But will return `401` if the page does not contain that taxonomy value, since `bob` does not have permission to read/edit/delete "generic" pages.

We'll make it so that `GET`, `PATCH` and `DELETE` methods for the `/pages` endpoint will accept the taxonomy role. 

For `POST`, it's a bit trickier, as I'm not sure if a user should be allowed to create _any_ page route. We can't know if there's a specific route (etc) that taxonomies _should_ belong to... Maybe we could adjust the handler so that it enforces that the page contains a taxonomy value matching a role possessed by the user. If it doesn't contain the header taxonomy info, it would return a `400` error, but that still allows the user a lot of freedom... at which point, you might as well just give them the `api.pages_create` role...? 🤷‍♂ 

What do you think about this?

**Comment by masetto** [comment]
@Regaez Yes, I agree, that would be very helpful.
What if, in addition to the boolean value of each rule, you also accept a structure such this?

rule as boolean (valid for all pages of the site):
```
access:
  api:
    pages_read: false
```
role based on taxonomy
```
access:
  api:
    pages_read:
        taxonomy:
            category: [blog, featured]
            tag: [foo, bar]
```
So you can also extend it for particular routes:
```
access:
  api:
    pages_read:
        url:
            - /blog
            - /staff/john
```
What do you think? Too complex?
Thanks

**Comment by Regaez** [comment]
@masetto I would have liked to have a structure like that! I experimented with more complex structures, such as you've proposed, but unfortunately there are a couple of issues:

1. [The Grav admin plugin's permissions template](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/permissions/permissions.html.twig) doesn't support nested fields, so you can't have a role like `api.pages_read.taxonomy` etc. or the template rendering will fail when you navigate to any user page (which is why I originally went with `api.pages_read` instead of `api.pages.read`). I could investigate fixing this in the admin plugin itself, but that's additional work outside the scope of this project, and I'm not sure if they would even want to accept a change like that. I would prefer to have the roles editable in the Admin UI, too, rather than create some special permission format that isn't compatible.
  
2. We're using the [`authorize` function from Grav core](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/User/Traits/UserTrait.php#L61-L103) to validate whether the user has the role. This _would_ work with nested properties, but the value of the final field must [match a value per the `Utils::isPositive()` function](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L1122), so that rules out your array idea. I don't really want to recreate the authorisation logic from Core within the API...

With the current implementation, both of these problems are avoided. You can add/remove the access rights from within the Admin UI (we register all the roles -- even custom taxonomy ones) and you can assign any user/group _any_ amount of taxonomy roles.

For example, instead of

```yaml
access:
  api:
    pages_read:
        taxonomy:
            category: [blog, featured]
            tag: [foo, bar]
```
This is how it would currently look in the account file:

```yaml
access:
  api:
    taxonomy_category___blog: true
    taxonomy_category___feature: true
    taxonomy_tag___foo: true
    taxonomy_tag___bar: true
```
And the only difference is that the user would receive GET/PATCH/DELETE rights for _any_ page with one of those taxonomy values. It would become crazy bloated if we were to split them apart by method, especially if the site has a few taxonomies. I don't think it's feasible to separate them in that way.

---

I could _perhaps_ imagine achieving your last example by introducing a custom user field and another custom role:
```yaml
access:
  api:
    pages_limited_access: true
page_access:
  read:
    - /secret-blog
    - /staff/john
  edit:
    - /staff/john
```
So if the user has the `api.pages_limited_access` role, they can only read/create/edit/delete page routes (and also descendant pages of those routes?) contained in the `page_access` object. But then you'd have to add all possible routes to this... it might get messy and it may not be very scalable.

I suppose we could also support the `page_access` field in a group, too. So you could inherit page access rights from a user's group, to reduce the number of users you would have to apply it to... 

I think this should be a separate issue though. I don't think this counts as "taxonomy" anymore. 😅

**Comment by masetto** [comment]
@Regaez I understand and it's okay how you propose. Already having permission based on taxonomies is a big step forward. Thanks.

**Comment by Regaez** [comment]
@masetto I've been giving it a bit of thought since I wrote the last message and I think I might investigate a more complex solution, which would ultimately be more flexible and scalable.

I don't really like how many custom roles the current implementation would generate if your site has a lot of taxonomies. It'll get ugly really fast. But perhaps adopting a solution, like you suggested, with passing a taxonomy object, could be more elegant.

Based on the idea for how we could do `route` based permissions:

_accounts/john.yaml_
```yaml
access:
  api:
    pages_advanced_access: true
api:
  advanced_access:
    pages:
      get:
        routes:
          - /staff-blog   # Can only read this page
          - /staff-blog/* # Can read any descendents of this page
        taxonomy:
          category:
            - staff-blog  # Instead of /staff-blog/*, you could use a taxonomy
            - staff       # Can read any pages with this taxonomy value
      post: 
        routes:
          - /staff/john   # Can only create this page
          - /staff-blog/* # Can create descendents of /staff-blog
      patch:
        routes:
          - /staff/john   # Can only edit this page
          - /staff/john/* # Can edit any descendents of /staff/john
        taxonomy:
          category:
            - staff-blog  # Can edit any page with this taxonomy value
      delete:
        routes:
          - /staff/john   # Can only delete this page
          - /staff-blog/* # Can delete any descendents of /staff-blog
        taxonomy:
          category:
            - staff-blog  # Can delete any page with this taxonomy value

```
Instead of generating a whole bunch of custom roles for each and every taxonomy, there would simply be one `api.pages_advanced_access` role. In addition to this, the user will need to have a custom user field which defines the route or taxonomy-based permissions for each type of API method. 

This would _only_ be applicable to the `pages` resource. I don't think it's necessary to extend it to `config`, or `plugins`. I do see potential in supporting `users` (where you could perhaps read/create/edit/delete users based on `group`), but that's for advanced user management and will be a separate feature.

We will still authenticate the user using the `AuthMiddleware`, validate their roles, but when you have the `api.pages_advanced_access` role, we allow them through and in the endpoint handler, similar to how it is currently implemented, compare the requested page resource with the users available routes/taxonomy permissions. 

This comparison would be a bit more complicated that the current implementation which uses `$user->authorize()`, but if we have already authenticated them in the middleware, then we don't need to rely on the `authorize()` function _again_, since we know they have the role already. We can potentially intersect the arrays to compare taxonomies, and check if the requested page route exists in the routes array.

One thing we need to take into account are groups. It would also be great to allow for advanced access by group, too, so we should make sure we consider the user's groups when making the comparison.

In addition to this, we can also extend the user account blueprint to include a nice form interface on the Admin profile page, so you can easily configure the API's advanced access object without having to touch the account yaml.
